#!/bin/bash
#./fit_surfaces HASH X_CENTER Y_CENTER LOWER_Y UPPER_Y SURFACE_TYPE OUTPUT_FILE_NAME MONTHS

export PATH="/usr/lib64/qt-3.3/bin:/usr/kerberos/bin:/opt/intel_fc_80/bin:/local/ups/prd/ups/v4_7_1/Linux-2/bin:/home/ugrad/rbarnes/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/local/linux/pkg/tecplot10/bin:/usr/opt/condor/bin"

./do_monthly_temp -P temp/$1.avg -a products/$1.stations $8 -s ushcn_monthly/ushcn-stations.txt -m ushcn_monthly/9641C_200912_F52.avg

./do_monthly_prcp -P temp/$1.prcp -a products/$1.stations $8 -s ushcn_monthly/ushcn-stations.txt -m ushcn_monthly/9641C_200912_F52.pcp

cat matlab_stack/CALL_SURFACES | sed -e "s/MONTHLY_PRCP/..\/temp\/$1.prcp/" -e "s/MONTHLY_TAVG/..\/temp\/$1.tavg/" -e "s/SAVE_NAME/..\/products\/$7.matlab_fitted/" -e "s/UPPER_Y/$5/" -e "s/LOWER_Y/$4/" -e "s/CENTER_X/$2/" -e "s/CENTER_Y/$3/" -e "s/SURF/$6/" > temp/$7.matlab_fit_surfaces

unset DISPLAY
cd matlab_stack
matlab < ../temp/$7.matlab_fit_surfaces
#mv $1.matlab_fitting ../products/$7
