#!/bin/bash
cd data/ahccd
./gen_station_list
cd ../..

cd data/ushcn_monthly
./gen_station_list
cd ../..

echo "lat\tlon\ttitle\tdescription"           >  stations.dat
cat data/ahccd/formatted_stations.dat         >> stations.dat
cat data/ushcn_monthly/formatted_stations.dat >> stations.dat
