#!/bin/bash
cd data/ahccd
./gen_station_list
cd ../..

cd data/ushcn_monthly
./gen_station_list
cd ../..

echo -e "lat\tlon\ttitle\tdescription"        >  stations.dat
cat data/ahccd/formatted_stations.dat         >> stations.dat
cat data/ushcn_monthly/formatted_stations.dat >> stations.dat

cd src/
make
cd ..
mv src/do_monthly_prcp.exe ./
mv src/do_monthly_temp.exe ./
